#!/bin/sh

set -e

if [ -e /home/user/.config/cuteTube/cuteTube.conf ]
    then
        echo 'Removing old cuteTube config file'
        su -c 'rm /home/user/.config/cuteTube/cuteTube.conf' - user
fi

if [ -e /home/user/cuteTube/cuteTube.sqlite ]
    then
        echo 'Removing old cuteTube database'
        su -c 'rm /home/user/cuteTube/cuteTube.sqlite' - user
fi

exit 0