#!/bin/sh

set -e

if [ -e /opt/cutetube/bin/cutetubeevents ] && [ -e /usr/share/dbus-1/services/com.maemo.cuteTubeEvents.service ]
    then
        echo 'Removing cuteTube events from event feed'
        su -c 'dbus-send --print-reply --type=method_call --dest=com.maemo.cuteTubeEvents / com.maemo.cuteTubeEvents.disableSync' - user
fi

exit 0
